#!/bin/bash
#
# Example usage:
#    script/generate-seamless-img $OUTPUT_IMG $STATE_GEOJSON ARCSEC_RESOLUTION
#    script/generate-seamless-img data/img/oregon.img data/json/states/oregon.json 1
#    script/generate-seamless-img data/img/oregon.img data/json/states/oregon.json 13
out_img=$1
target_data=$2
resolution=$3
buffer_miles=$4

# Given a $target_data feature, find the DEM grids that intersect with it
grid_tiles=$(ndjson-join 'true' <(cat $target_data) <(cat static/grid-${resolution}.json) \
  | ndjson-filter -r geom=./script/geom.js "geom.intersect(geom.buffer(geom.envelope(d[0]), $buffer_miles, 'miles'), d[1])" \
  | ndjson-map 'd[1].properties.FILE_ID')

img_paths=""
for grid in $grid_tiles; do
  file_id=$(echo $grid | tr -d '"')
  img_file=data/img/usgs/dem/$resolution/$file_id.img
  make $img_file
  img_paths+="$img_file "
done

echo "Merging to $out_img"
gdal_merge.py \
    -n -3.4028234663852886e+38 \
    -a_nodata -99999 \
    -init 255 \
    -o $out_img $img_paths

echo "Data directory is at $(du -sh data)"
