#!/usr/bin/env node
// Generates a series of colors using sequential scales.  Output can either be a list of rgb()
// values or color ramp files for gdaldem color-relief images.
//
// Examples:
//  Generate ramp format getting min/max elevation from the input tif
//    generate-ramp -c 10 --ramp --tif data/tif/states/oregon.tif
//
//  Use Viridis interpolation.  See https://github.com/d3/d3-scale#sequential-scales.  Case-sensitive.
//    generate-ramp --interpolate Viridis --ramp --tif data/tif/states/oregon.tif > static/viridis.ramp
//
//  Generate 25 rgb() colors beween a range of 10-100
//    generate-ramp -c 25 --min 10 --max 100
//
//
var d3 = require('d3'),
    commander = require('commander'),
    exec = require('child_process').execSync

var hue = d3.randomUniform(360)(),
    c1 = d3.hsl(Math.round(hue), 1, 0.5),
    c2 = d3.hsl(Math.round(hue) + 90, 1, 0.5)

commander
  .version(require("../package.json").version)
  .option('-mi, --min <n>', 'min range value')
  .option('-ma, --max <n>', 'max range value')
  .option('-c, --count <n>', 'Number of colors to return')
  .option('-c1, --color1 <c>', 'start color', c1.toString())
  .option('-c2, --color2 <c>', 'end color', c2.toString())
  .option('--ramp', 'generate ramp')
  .option('-t, --tif <img>', 'get min and max from GeoTif stats.')
  .option('-i, --interpolate <interpolater>', 'Set the interpolater', 'Inferno')
  .parse(process.argv);

if(commander.tif) {
  var out = exec('gdalinfo -stats -json ' + commander.tif, { encoding: 'utf-8' })
  var data = JSON.parse(out)
  commander.min = data.bands[0].min
  commander.max = data.bands[0].max
}

var scale = d3.scaleSequential(d3['interpolate' + commander.interpolate])
  .domain([commander.min, commander.max])

scale.ticks(commander.count).map((v) => {
  var c = d3.rgb(scale(v))
  if(commander.ramp) {
    console.log(v + ' ' + c.r + ' ' + c.g + ' ' + c.b);
  } else {
    console.log(c.toString())
  }
})
