#!/bin/bash

# Oregon Lambert EPSG:2991
# +proj=lcc +lat_1=43 +lat_2=45.5 +lat_0=41.75 +lon_0=-120.5 +x_0=400000 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs
# california Albers EPSG:3310
# +proj=aea +lat_1=34 +lat_2=40.5 +lat_0=0 +lon_0=-120 +x_0=0 +y_0=-4000000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs
#
#

geo2topo -n state=<(shp2json -n data/shp/states.shp \
  | ndjson-filter 'd.properties.NAME == "Oregon"') \
  | toposimplify -P 0.2 -f \
  | topoquantize 1e5 \
  > public/oregon-topo.json
